services:
  db:
    image: postgres:15
    container_name: real_estate_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realestate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: real_estate_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env           
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
